version: '3.9'
name: cruise-company-backend

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 10s
  x-mysql: &healthcheck-mysql
    test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]

services:
  cs-cos-backend-my-sql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cruise_company
    ports:
      - "3307:3306"
    healthcheck:
      <<: [ *healthcheck, *healthcheck-mysql ]
  cs-qes-backend-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cruise_company_subscribers
    ports:
      - "3308:5432"
  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
  cs-qes-backend-mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: statistics
    ports:
      - '27017:27017'
