version: '3.9'
name: cruise-company-all
services:
  postgres-db:
    env_file: .env
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
  my-sql:
    env_file: .env
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
  activemq:
    env_file: .env
    image: symptoma/activemq:latest
    ports:
      - ${ACTIVEMQ_LOCAL_PORT}:${ACTIVEMQ_DOCKER_PORT}
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVEMQ_ADMIN_LOGIN}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
      ACTIVEMQ_WEBADMIN_USERNAME: ${ACTIVEMQ_WEBADMIN_USERNAME}
      ACTIVEMQ_WEBADMIN_PASSWORD: ${ACTIVEMQ_WEBADMIN_PASSWORD}
  mongo-db:
    env_file: .env
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_LOCAL_PORT: ${MONGODB_LOCAL_PORT}
      MONGODB_DOCKER_PORT: ${MONGODB_DOCKER_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
  spring-boot-app:
    env_file: .env
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - postgres-db
      - my-sql
      - activemq
      - mongo-db
