kafka:
  bootstrap-servers: localhost:9092
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: cruise-company
    auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: '*'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cruise_company
      username: root
      password: root
topic:
  name:
    new-cruise-ship: new-cruise-ship