server:
  port: 8082
  servlet:
    context-path: /cruise-company
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
data:
  mongodb:
    uri: mongodb://localhost:27017/statistics
    auto-index-creation: true

