spring:
  application:
    name: tc-iam-backend
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queues:
      cruise-ship: cruise-ships
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false

  swagger-ui:
    path: /swagger-ui.html
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
server:
  port: ${SERVER_PORT}

