spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cruise_company
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  swagger-ui:
    path: /swagger-ui.html
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 8081
kafka:
  topic:
    name:
      new-cruise-ship: new-cruise-ship