server:
  port: 8082
  servlet:
    context-path: /
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:3308/cruise_company_subscribers
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  swagger-ui:
    path: /swagger-ui.html
data:
  mongodb:
    uri: mongodb://localhost:27017/statistics
    auto-index-creation: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970